// <auto-generated />
namespace AI_WoundAnalysisSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class woundTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(woundTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "201801221141060_woundTbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
